name: Ship CRISPR workflow

on:
  push:
    branches: ["master","development"]
  pull_request:
    branches: ["master","development"]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        # Test all supported Python versions under Ubuntu
        os: [ubuntu-latest]
        python-version: ['3.12', '3.13']

    runs-on: ${{ matrix.os }}